log:
  level: debug
  disable_sentry: true

db:
  url: postgres://points:points@localhost:5432/points?sslmode=disable

listener:
  addr: localhost:8000

event_types:
  passport_rewards:
      age: 20
      nationality: 50
  types:
    - name: passport_scan
      title: Points for passport scan
      reward: 200
      description: Get points for scan passport and share data
      short_description: Short description
      frequency: one-time
      actional_url: https://...
    - name: get_poh
      title: Get PoH credential
      reward: 50
      description: Prove that you are human
      short_description: Short description
      frequency: one-time
      expires_at: 2020-01-01T00:00:00Z
    - name: free_weekly
      title: Free weekly points
      reward: 100
      frequency: weekly
      description: Get free points every week by visiting the platform and claiming your reward
      short_description: Short description
    - name: daily_login
      title: Daily login
      reward: 5
      frequency: daily
      description: Login every day
      short_description: Short description
      disabled: true
    - name: be_referred
      title: Referral welcome bonus
      reward: 5
      frequency: one-time
      description: Be referred by a friend and get a welcome bonus
      short_description: Short description
      no_auto_open: true
    - name: referral_common
      title: Refer new users
      reward: 25
      frequency: one-time
      description: Refer friends and get a reward for each friend who verifies the passport
      short_description: Short description
    - name: referral_specific
      title: Refer user {:did}
      reward: 25
      frequency: unlimited
      description: The user {:did} has verified the passport. Claim the reward!
      short_description: Short description
      no_auto_open: true
    - name: planned
      title: Planned event
      reward: 25
      frequency: unlimited
      description: Event that start at specidied time
      short_description: Short description
      starts_at: 2020-01-01T00:00:00Z

auth:
  addr: http://rarime-auth

broadcaster:
  addr: broadcaster
  sender_account: "rarimo15hcd6tv7pe8hk2re7hu0zg0aphqdm2dtjrs0ds"

withdrawal:
  point_price_urmo: 100

sbt_check:
  networks:
    - name: polygon
      rpc: https://your-rpc
      contract: 0x...
      request_timeout: 5s
      start_from_block: 48984542
      block_window: 3
      max_blocks_per_request: 5000
    - name: ethereum
      rpc: https://your-rpc
      contract: 0x...
      request_timeout: 5s
    - name: disabled_sample
      disabled: true
      rpc: https://your-rpc
      contract: 0x...
      request_timeout: 5s
