log:
  level: debug
  disable_sentry: true

db:
  url: postgres://points:points@localhost:5432/points?sslmode=disable

listener:
  addr: localhost:8000

event_types:
  types:
    - name: passport_scan
      title: Points for passport scan
      reward: 5
      description: Get points for scan passport and share data
      short_description: Short description
      frequency: one-time
      action_url: https://...
      logo: https://...
    - name: free_weekly
      title: Free weekly points
      reward: 1
      frequency: weekly
      description: Get free points every week by visiting the platform and claiming your reward
      short_description: Short description
    - name: be_referred
      title: Referral welcome bonus
      reward: 1
      frequency: one-time
      description: Be referred by a friend and get a welcome bonus
      short_description: Short description
      no_auto_open: true
    - name: referral_common
      reward: 1
      frequency: one-time
      title: Refer new users
      short_description: Refer friends and get a reward for each friend who verifies the passport
      description: Refer friends and get a reward for each friend who verifies the passport
    - name: referral_specific
      title: Refer user {:did}
      reward: 1
      frequency: unlimited
      description: The user {:did} has verified the passport. Claim the reward!
      short_description: Short description
      no_auto_open: true

levels:
  levels:
    - lvl: 1
      threshold: 0
      referrals: 5
      withdrawal_allowed: false
    - lvl: 2
      threshold: 5
      referrals: 5
      withdrawal_allowed: true
    - lvl: 3
      threshold: 6
      referrals: 5
      withdrawal_allowed: true

countries:
  countries:
    - code: "UKR"
      reserve_limit: 100000
      reserve_allowed: true
      withdrawal_allowed: true
    - code: "USA"
      reserve_limit: 5
      reserve_allowed: true
      withdrawal_allowed: true
    - code: "GBR"
      reserve_limit: 5
      reserve_allowed: false
      withdrawal_allowed: true
    - code: "default"
      reserve_limit: 5
      reserve_allowed: true
      withdrawal_allowed: true

auth:
  addr: http://rarime-auth

broadcaster:
  addr: broadcaster
  sender_account: "rarimo15hcd6tv7pe8hk2re7hu0zg0aphqdm2dtjrs0ds"

verifier:
  verification_key_path: "./verification_key.json"
  allowed_age: 18
  allowed_identity_timestamp: 1715698750

root_verifier:
  rpc: evm_rpc_url
  contract: registration_contract_address
  request_timeout: 10s

withdrawal:
  point_price_urmo: 100

sbt_check:
  networks:
    - name: polygon
      rpc: https://your-rpc
      contract: 0x...
      request_timeout: 5s
      start_from_block: 48984542
      block_window: 3
      max_blocks_per_request: 5000
    - name: ethereum
      rpc: https://your-rpc
      contract: 0x...
      request_timeout: 5s
    - name: disabled_sample
      disabled: true
      rpc: https://your-rpc
      contract: 0x...
      request_timeout: 5s
