log:
  level: debug
  disable_sentry: true

db:
  url: postgres://points:points@localhost:5432/points?sslmode=disable

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: rarime-points-svc
  service_port: 80

event_types:
  types:
    - name: get_poh
      title: Get PoH credential
      reward: 50
      description: Lorem ipsum dolor sit amet
      frequency: one-time
      expires_at: 2020-01-01T00:00:00Z
    - name: daily_login
      title: Daily login
      reward: 5
      frequency: daily
      description: Lorem ipsum dolor sit amet

auth:
  addr: http://rarime-auth

broadcaster:
  addr: "http://broadcaster"
  sender_account: "rarimo1..."
