allOf:
  - $ref: '#/components/schemas/CountriesConfigKey'
  - type: object
    required:
      - attributes
    properties:
      attributes:
        type: object
        required:
          - countries
        properties:
          countries:
            type: array
            description: |
              Array of codes and their properties.
              Each code is ISO 3166-1 alpha-3 code (3-letter uppercase).
            items:
              $ref: '#/components/schemas/CountryProperties'
