allOf:
  - $ref: '#/components/schemas/CountriesConfigKey'
  - type: object
    required:
      - attributes
    properties:
      attributes:
        type: object
        required:
          - countries
        properties:
          countries:
            type: object
            additionalProperties:
              $ref: '#/components/schemas/CountryProperties'
