on:
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  lint:
    name: code-review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          reporter: github-pr-review
          cache: false
